---
title: "Featurize PPIs"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(reticulate)
use_condaenv("rpy3_tmp")
Sys.setenv("RETICULATE_PYTHON"="/home/users/bentyeh/miniconda3/envs/rpy3_tmp/bin/python")
options(stringsAsFactors = FALSE)

if (.Platform$OS.type == "unix") {
    projectDir = normalizePath("~/projects/disprot")
    source("~/scripts/R/utils-convert.R")
} else {
    projectDir = normalizePath("~/Projects/disprot")
    source("~/Projects/scripts_private/R/utils-convert.R")
}
files = reticulate::import_from_path(module='files', path=file.path(projectDir, 'scripts'))
paths = files$getPaths()
source(file.path(projectDir, 'scripts', 'featurize.R'))
```

# Parameters for this script

```{r params}
cores = 31
```

# Features database

Read in features database or create it if it does not exist

```{r featuresDB}
featuresDB = createFeaturesDB(paths[['uniprotProteome']], save = paths[['featuresDB_full_0']], lambda = 0, cores = cores)
featuresDB = createFeaturesDB(paths[['uniprotProteome']], save = paths[['featuresDB_full_50']], lambda = 50, cores = cores,
                              features = c("APAAC", "PAAC", "Geary", "Moran", "MoreauBroto", "QSO", "SOCN"))
```

```{r}
featuresDB_full_0 = readRDS(paths[['featuresDB_full_0']])
featuresDB_full_50 = readRDS(paths[['featuresDB_full_50']])
ids = intersect(names(featuresDB_full_50[[1]]), names(featuresDB_full_0[[1]]))

featuresDB_full = c(featuresDB_full_0, featuresDB_full_50)
for (feature in names(featuresDB_full)) {
  featuresDB_full[[feature]] = featuresDB_full[[feature]][ids]
}
```

```{r}
dataAll_trim = readr::read_tsv(paths[['IDPpi_dataAll_trim']])
valid = (dataAll_trim[["p1_uniprotName"]] %in% ids) & (dataAll_trim[["p2_uniprotName"]] %in% ids)
print(paste("number of invalid:", sum(!valid)))
dataAll_trim = dataAll_trim[valid,]
featuresAll_trim = matchFeatures(dataAll_trim, featuresDB_full,
  features = c('AAC', 'CTDD', 'CTDT', 'CTriad', 'DC', 'APAAC', 'Geary', 'Moran', 'MoreauBroto', 'QSO', 'SOCN'),
  dataset_cols = c("p1_uniprotName", "p2_uniprotName"),
  features_path = paths[['IDPpi_featuresAll_noTC_trim_unc']],
  labels_path = paths[['IDPpi_labelsAll_trim']])
```

```{r}
nCols = ncol(featuresAll_trim)
aug = cbind(featuresAll_trim[,(nCols/2+1):nCols], featuresAll_trim[, 1:(nCols/2)])
names(aug) = names(featuresAll_trim) # rbind() requires non-null matching column names
featuresAll_aug = rbind(featuresAll_trim, aug)
rm(aug)
```

```{r}
p = prcomp(featuresAll_aug, scale.=TRUE)
featuresPCA = p$x[,p$sdev > 1]
readr::write_tsv(as.data.frame(featuresPCA), paths[['IDPpi_featuresPCA_unc']])
```
